Final project
nikson1701/gbCourse4Hw pull request #8
Opened 2021-08-18 07:46 UTC by nikson1701

Взят сайт, сверстанный на 2 курсе по профессиональной верстке
Что сделано:
- Фронт переделан с использованием Vue JS, настроена маршрутизация с использованием Vue Router
- Серверная часть взята с курса по продвинутому JS, используется Node JS
- Сборка с помощью Webpack
Что сделано на сайте:
- Переход на главную по нажатию на логотип в верхнем левом углу
- Переход на страницу каталога по кнопке "Browse all product" после товаров на главной странице
- Переход на страницу товара по нажатию на имя товара
- Добавление товара по кнопке Add to cart на товаре или на странице товара
- Переход на страницу корзины по кнопке перейти в корзину , которая появляется при открытии корзины в верхнем правом углу
- В корзине можно изменить количество определенного товара стрелками, полностью удалить товар крестиком и очистить корзину по кнопке Clear shopping cart
- Также есть статичная страница регистрации

2021-08-28 14:29 UTC, Om1X requested changes
Основная и довольно критическая ошибка, связана с использованием нативных js способов манипуляции с DOM и событиями. Нужно избавиться от них, переписав, используя Vue инструментарий.

2021-08-28 14:29 UTC, Om1X commented on src/public/index.js
> +}
такого рода манипуляции с DOM и событиями не допустимы в фреймворках. Все должно быть реализовано через инструментарий, который имеется у самого фреймворка. Все должны быть собрано на уровне компонента.

2021-08-28 14:29 UTC, Om1X commented on src/public/index.js
> +    },
можно удалить

2021-08-28 14:29 UTC, Om1X commented on src/public/index.js
> +    },
тоже удаляем

2021-08-28 14:29 UTC, Om1X commented on src/public/js/CartComp.js
> +	},
удаляем

2021-08-28 14:29 UTC, Om1X commented on src/public/js/CartPageComp.js
> +	},
удаляем

2021-08-28 14:29 UTC, Om1X commented on src/public/js/CartPageComp.js
> +	},
и тут удаляем

2021-08-28 14:29 UTC, Om1X commented on src/public/js/CatalogComp.js
> +	},
и тут удаляем

2021-08-28 14:29 UTC, Om1X commented on src/public/js/CatalogItemComp.js
> +	},
тоже удаляем пустое свойство

2021-08-28 14:29 UTC, Om1X commented on src/public/js/CatalogPageComp.js
> +}
аналогично замечанию выше, касательно нативных манипуляций с DOM и событиями

2021-08-28 14:29 UTC, Om1X commented on src/public/js/PageCartComp.js
> +	},
удаляем

2021-08-28 14:29 UTC, Om1X commented on src/public/js/PageCartComp.js
> +	},
удаляем

2021-08-28 14:29 UTC, Om1X commented on src/public/js/PageCatalogComp.js
> +}
аналогично двум замечаниям выше

2021-08-28 14:29 UTC, Om1X commented on src/public/js/PageProductComp.js
> +}
и тут тоже

2021-08-28 14:29 UTC, Om1X commented on src/public/js/PageRegistrationComp.js
> +	},
удалить

2021-08-28 14:29 UTC, Om1X commented on src/public/js/ProductPageComp.js
> +}
аналогично похожим замечаниям выше

2021-08-28 14:29 UTC, Om1X commented on src/public/js/ProductPageComp.js
> +		}
удалить

2021-08-30 08:56 UTC, nikson1701 commented
Замечания устранены

2021-10-20 06:54 UTC, merged